name: Docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1-dev
          pip install sphinx sphinx_rtd_theme numpydoc recommonmark
          pip install mirdata
          pip install scikit-learn 
          pip install configobj
          pip install hmmlearn
          pip install fastdtw
          pip install matplotlib
          pip install scipy
          pip install essentia
          pip install tensorflow
          pip install torch 
          pip install ipython
          pip install scikit-image
          pip install seaborn
          pip install opencv-python
          pip install smart_open
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true